galaxy_info:
  author: Mats Blomdahl
  description: Provisioning of accounts/keys and commonly used libraries, utilities and configurations.

  license: MIT

  min_ansible_version: 2.2

  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - common

dependencies: []
