galaxy_info:
  author: Viktoriia Tepliuk
  description: Jenkins 2.60 installation.

  license: MIT

  min_ansible_version: 2.2

  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - jenkins

dependencies: []
