---

- name: add 'jenkins' user to 'docker' group
  user: name=jenkins groups=docker append=yes

- name: allow incoming traffic on port 8080
  firewalld: port=8080/tcp permanent=true state=enabled immediate=yes
  notify: restart firewalld

- name: replace line for disabling security
  lineinfile:
    dest: /var/lib/jenkins/config.xml
    regexp: '  <useSecurity>true</useSecurity>'
    line: '  <useSecurity>false</useSecurity>'
  notify: restart jenkins

- name: jenkins running and enabled
  service: name=jenkins state=started enabled=yes

- name: wait for Jenkins to start up
  uri:
    url: http://{{ ansible_eth0.ipv4.address }}:8080
    status_code: 200
    timeout: 5
  register: jenkins_service_status
  # Keep trying for 5 mins in 5 sec intervals
  retries: 60
  delay: 5
  until: >
     'status' in jenkins_service_status and
     jenkins_service_status['status'] == 200

- name: install github plugin
  jenkins_plugin:
    name: github
    version: '1.28.0'

- name: install publish-over-ssh plugin
  jenkins_plugin:
    name: publish-over-ssh
    version: '1.17'

- name: install ssh plugin
  jenkins_plugin:
    name: ssh
    version: '2.5'



...