---

- name: jenkins running and enabled
  service: name=jenkins state=started enabled=yes

- name: allow incoming traffic on port 8080
  firewalld: port=8080/tcp permanent=true state=enabled
  notify: restart firewalld

- name: Jenkins - configure | Turn off Jenkins setup wizard
  lineinfile: dest=/etc/sysconfig/jenkins regexp='^JENKINS_JAVA_OPTIONS=' line='JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
  notify: restart jenkins
...
