---

- name: add 'jenkins' user to 'docker' group
  user: name=jenkins groups=docker append=yes
  tags: docker

- name: jenkins running and enabled
  service: name=jenkins state=started enabled=yes

- name: allow incoming traffic on port 8080
  firewalld: port=8080/tcp permanent=true state=enabled
  notify: restart firewalld

...
