---

- name: set hostname
  hostname: name="{{inventory_hostname}}"

- name: bind own hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1   {{ inventory_hostname }}"

- name: set timezone utc
  copy: src=/usr/share/zoneinfo/UTC dest=/etc/localtime

- name: create 'supergroup' group
  group: name=supergroup

- name: add 'root' user to 'supergroup' and 'wheel'
  user: name=root groups=supergroup,wheel append=yes

- name: allow 'wheel' group to run password-less sudo without requiretty
  blockinfile:
    dest: /etc/sudoers
    marker: "# {mark} ANSIBLE MANAGED BLOCK accounts"
    block: |
      %wheel ALL=(ALL) NOPASSWD: ALL
      Defaults!/usr/bin/docker !requiretty
      Defaults:%wheel !requiretty
      Defaults:%wheel visiblepw
    validate: visudo -cf %s

...
