---

- name: docker-ce repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: install docker-ce-17.06.1.ce
  yum: name=docker-ce-17.06.1.ce state=present
  notify: restart docker

...
